FROM alpine:edge
LABEL org.opencontainers.image.authors="Peter Bottenberg <cyberjack77@gmail.com>" \
      description="Lightweight container to run PHP in ci jobs."

# Install composer
COPY --from=composer:1.10 /usr/bin/composer /usr/bin/composer1
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Add the ci user and group, and install packages and remove default server definition
RUN addgroup -S ci \
    && adduser -S \
      -h /home/ci \
      -s /bin/bash \
      -G root \
      -G ci \
      -u 1000 ci \
    \
    && apk --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing add \
    bash \
    curl \
    findutils \
    git \
    openssh-client \
    patch \
    php83 \
    php83-bcmath \
    php83-ctype \
    php83-curl \
    php83-dom \
    php83-ffi \
    php83-fileinfo \
    php83-ftp \
    php83-gd \
    php83-iconv \
    php83-imap \
    php83-intl \
    php83-json \
    php83-mbstring \
    php83-mysqli \
    php83-openssl \
    php83-pcntl \
    php83-pdo_mysql \
    php83-pdo_pgsql \
    php83-pdo_sqlite \
    php83-pecl-amqp \
    php83-pecl-mongodb \
    php83-pgsql \
    php83-phar \
    php83-phpdbg \
    php83-posix \
    php83-session \
    php83-simplexml \
    php83-soap \
    php83-sockets \
    php83-sodium \
    php83-tokenizer \
    php83-xml \
    php83-xmlreader \
    php83-xmlwriter \
    php83-xsl \
    php83-zip \ 
    rsync \
    zip \
    \
    # Setup working directories
    && mkdir -p /app \
    && chown -R ci:ci /app \
    \
    # Prepare bash usage
    && echo "alias ll=\"ls -alFh\"" >> /home/ci/.bashrc \
    && chown ci:ci /home/ci/.bashrc

COPY ./php-ini-overrides.ini /etc/php83/conf.d/

ENV PATH="/home/ci/.composer/vendor/bin:${PATH}"
WORKDIR /app

USER ci

RUN composer1 config --global repo.packagist composer https://packagist.org

CMD ["/bin/bash"]
