FROM alpine:edge
LABEL org.opencontainers.image.authors="Peter Bottenberg <cyberjack77@gmail.com>" \
      description="Lightweight container to run PHP in ci jobs."

# Install composer
COPY --from=composer:1.10 /usr/bin/composer /usr/bin/composer1
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Add the ci user and group, and install packages and remove default server definition
RUN addgroup -S ci \
    && adduser -S \
      -h /home/ci \
      -s /bin/bash \
      -G root \
      -G ci \
      -u 1000 ci \
    \
    && apk --no-cache add \
    bash \
    curl \
    findutils \
    git \
    openssh-client \
    patch \
    php82 \
    php82-bcmath \
    php82-ctype \
    php82-curl \
    php82-phpdbg \
    php82-dom \
    php82-ffi \
    php82-fileinfo \
    php82-ftp \
    php82-gd \
    php82-iconv \
    php82-imap \
    php82-intl \
    php82-json \
    php82-mbstring \
    php82-mysqli \
    php82-openssl \
    php82-pcntl \
    php82-pdo_mysql \
    php82-pdo_pgsql \
    php82-pdo_sqlite \
    php82-pecl-amqp \
    php82-pecl-mongodb \
    php82-pgsql \
    php82-phar \
    php82-phpdbg \
    php82-posix \
    php82-session \
    php82-simplexml \
    php82-soap \
    php82-sockets \
    php82-sodium \
    php82-tokenizer \
    php82-xml \
    php82-xmlreader \
    php82-xmlwriter \
    php82-xsl \
    php82-zip \ 
    rsync \
    zip \
    \
    # symlink php8 to php
    && ln -s /usr/bin/php82 /usr/bin/php \
    && ln -s /usr/bin/phpdbg82 /usr/bin/phpdbg \
    \
    # Setup working directories
    && mkdir -p /app \
    && chown -R ci:ci /app \
    \
    # Prepare bash usage
    && echo "alias ll=\"ls -alFh\"" >> /home/ci/.bashrc \
    && chown ci:ci /home/ci/.bashrc

COPY ./php-ini-overrides.ini /etc/php82/conf.d/

ENV PATH="/home/ci/.composer/vendor/bin:${PATH}"
WORKDIR /app

USER ci

RUN composer1 config --global repo.packagist composer https://packagist.org

CMD ["/bin/bash"]
